matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#os: linux
dist: trusty
language: cpp
compiler: gcc-5
group: deprecated-2017Q2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qtscript5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev libboost-all-dev
    # Install zlib
  - v=1.2.8  
  - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4/zlib-${v}.tar.gz
  - tar -xf zlib-${v}.tar.gz && cd zlib-${v}
  - ./configure --prefix=/usr/local
  - #sudo make check install
  - sudo make install
  - cd ..
    # Install HDF5
  - v=1.8.13
  - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4/hdf5-${v}.tar.gz
  - tar -xf hdf5-${v}.tar.gz && cd hdf5-${v}
  - prefix="/usr/local/hdf5-$v"
  - if [ $HDF5_DIR != $prefix ]; then
  -     echo "Add HDF5_DIR=$prefix to .bashrc"
  -     echo "" >> $BASHRC
  -     echo "# HDF5 libraries for python" >> $BASHRC
  -     echo export HDF5_DIR=$prefix  >> $BASHRC
  - fi
  - ./configure --enable-shared --enable-hl --prefix=$HDF5_DIR
  - make -j 2 # 2 for number of procs to be used
  - sudo make install
  - cd ..
    # Install Netcdf
  - v=4.1.3
  - wget http://www.unidata.ucar.edu/downloads/netcdf/ftp/netcdf-${v}.tar.gz
  - tar -xf netcdf-${v}.tar.gz && cd netcdf-${v}
  - prefix="/usr/local/"
  - if [ $NETCDF4_DIR != $prefix ]; then
  -     echo "Add NETCDF4_DIR=$prefix to .bashrc"
  -     echo "" >> $BASHRC
  -     echo "# NETCDF4 libraries for python" >> $BASHRC
  -     echo export NETCDF4_DIR=$prefix  >> $BASHRC
  - fi
  - CPPFLAGS=-I$HDF5_DIR/include LDFLAGS=-L$HDF5_DIR/lib ./configure --enable-netcdf-4 --enable-shared --enable-dap --prefix=$NETCDF4_DIR
    # make check
  - make 
  - sudo make install
  - cd ..
  - eval "${MATRIX_EVAL}"

sudo: required

script:
  - export QT_SELECT=qt5
  - export CXX="g++-5"
  - export CC="gcc-5"
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - g++ -v
  - gcc -v
  - qmake -qt=qt5 -v
  - qmake -qt=qt5 CONFIG+=release -o Makefile build.pro
  - make -j4
  - ./bin/MavenTests -xml
