os: linux
dist: trusty
language: cpp
compiler: gcc
before_install:
  - sudo apt-get update -y
  - sudo apt-get install g++ -y
  - sudo apt-get install qt4-dev-tools qt4-qmake libboost-all-dev -y
script:
  - export QT_SELECT=qt4
  - qmake CONFIG+=release -o Makefile build.pro
  - make -j4
