title: El Maven
author: Elucidata
email: http://elucidata.io
baseurl: "https://elucidatainc.github.io/ElMaven"
description: > # this means to ignore newlines until "baseurl:"
  An opensource LC-MS data processing engine 

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed