title: El Maven
author: Elucidata
email: http://elucidata.io
baseurl: "/ElMaven"
production_url : https://elucidatainc.github.io/ElMaven
BASE_PATH : https://github.com/ElucidataInc/ElMaven
description: > # this means to ignore newlines until "baseurl:"
  An opensource LC-MS data processing engine 

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed