title: El-MAVEN
author: Elucidata
email: elmaven@elucidata.io
baseurl: "/ElMaven"
production_url : https://resources.elucidata.io/elmaven
BASE_PATH : https://github.com/ElucidataInc/ElMaven
description: > # this means to ignore newlines until "baseurl:"
  An open-source LC-MS data processing engine 

sass:
    style: compressed
